Der Vermögensstand wurde entfernt.
Polyfish0/school-ns-home pull request #3
Opened 2023-05-23 09:35 UTC by janamueller

2023-05-25 09:35 UTC, Polyfish0 requested changes
Auch hier bitte die Pflegeheim.iml aus dem PR nehmen

2023-05-25 09:37 UTC, janamueller commented
Die was?

2023-05-25 10:04 UTC, Polyfish0 commented
https://github.com/Polyfish0/school-ns-home/pull/3/files#diff-04806ecfa204d76c24755cbd9f1e88d8955903c698908af4a943e9c9b568de71

2023-06-12 06:46 UTC, Polyfish0 submitted a review, later dismissed

2023-06-13 06:51 UTC, Polyfish0 approved these changes

2023-06-13 06:52 UTC, merged